def dance():
    import os,time
    dots=os.system("cls")
    print (" | - | - | - | - | - | ")
    time.sleep(1)
    os.system("cls")
    print (" \ - \ - \ - \ - \ - \ ")
    time.sleep(1)
    os.system("cls")
    print (" / - / - / - / - / - / ")
    time.sleep(1)
    os.system("cls")
    print (" | - | - | - | - | - | ")
    time.sleep(1)
    os.system("cls")
    print (" \ - \ - \ - \ - \ - \ ")
    time.sleep(1)
    os.system("cls")
    print (" / - / - / - / - / - / ")
    time.sleep(1)
    os.system("cls")
    print (" | - | - | - | - | - | ")
    time.sleep(1)
    os.system("cls")
    print (" \ - \ - \ - \ - \ - \ ")
    time.sleep(1)
    os.system("cls")
    print (" / - / - / - / - / - / ")
    time.sleep(1)
    os.system("cls")
    print (" | - | - | - | - | - | ")
    time.sleep(1)
    os.system("cls")
    print (" \ - \ - \ - \ - \ - \ ")
    time.sleep(1)
    os.system("cls")
    print (" / - / - / - / - / - / ")
    time.sleep(1)
    os.system("cls")
    return dots

print (dance())