import os,time
def dance():
    print ()
    time.sleep(1)
    os.system("cls")
    print (" | - | - | - | - | - | ")
    time.sleep(1)
    os.system("cls")
    print (" X - X - X - X - X - X ")
    time.sleep(1)
    os.system("cls")
    print (" / - / - / - / - / - / ")
    time.sleep(1)
    os.system("cls")
    print (" | - | - | - | - | - | ")
    time.sleep(1)
    os.system("cls")
    print (" X - X - X - X - X - X ")
    time.sleep(1)
    os.system("cls")
    print (" / - / - / - / - / - / ")
    time.sleep(1)
    os.system("cls")
    print (" | - | - | - | - | - | ")
    time.sleep(1)
    os.system("cls")
    print (" X - X - X - X - X - X ")
    time.sleep(1)
    os.system("cls")
    print (" / - / - / - / - / - / ")
    time.sleep(1)
    os.system("cls")
    print (" | - | - | - | - | - | ")
    time.sleep(1)
    os.system("cls")
    print (" X - X - X - X - X - X ")
    time.sleep(1)
    os.system("cls")
    print (" / - / - / - / - / - / ")
    time.sleep(1)
    os.system("cls")
    dots= "🎵 Welcome to Music Player🎵"
    return dots

print (dance())

def play (number):
    songslist=number
    print ("Now playing song No.: ", number)
    return songslist
print ()
while True:
    print ("Music Menu:")
    print ("1. All Saints: Pure Shores")
    print ("2. U2: With Or Without You")
    print ("3. Radiohead: Creep")
    print ("4. Pink Floyd: Another Brick In The Wall")
    print ("5. The Rolling Stones: Paint It, Black")
    print ("6. AC/DC: Thunderstruck")
    print ("7. Led Zeppelin: Stairway to Heaven ")
    print ("8. Eagles: Hotel California")
    print ("9. The Beatles: Don't Let Me Down")
    print ("10. Queen: Bohemian Rhapsody")
    playExit=input("Enter play to choose a song / exit to end: ")
    if playExit.lower() =="exit":
        break
    choice=int(input("Enter song number: "))
    os.system("cls")
    play(choice) 
    print ()
